title: dmmax me
email: dmmax.me@gmail.com
baseurl: ""
url: https://dmmax.me
github_username: dmmax
description: Java Программист

permalink: /:slug.html

remote_theme: riggraz/no-style-please

goat_counter: dmmax
theme_config:
  appearance: "light"
  back_home_text: "Back"
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-sitemap