title: dmmax
email: dmmax.me@gmail.com
description: Жизнь и работа в Германии
baseurl: ""
url: https://dmmax.github.io
github_username: dmmax

permalink: /:slug.html

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light"
  back_home_text: "Back"
  date_format: "%Y-%m-%d"
  show_description: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag