# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

#theme: "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Settings
locale: "ru-RU"
github: #
#title: "Блог Java/Kotlin программиста"
title: "dmmax.me"
title_separator: "|"
masthead_title: "dmmax"
name: "Max"
description: "Блог Java/Kotlin разработчика"
url: http://dmmax.me
baseurl: # the subpath of your site, e.g. "/blog"
repository: dmmax/dmmax.github.io
teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs: true
words_per_minute: 120
collections:
  travel:
    output: true
    permalink: /:collection/:path/
comments:
  provider: # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname: # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server: # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid:
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"
  utterances:
    theme: # "github-light" (default), "github-dark"
staticman:
  allowedFields: # ['name', 'email', 'url', 'message']
  branch: # "master"
  commitMessage: # "New comment by {fields.name}"
  filename: # comment-{@timestamp}
  format: # "yml"
  moderation: # true
  path: # "/_data/comments/{options.slug}" (default)
  requiredFields: # ['name', 'email', 'message']
  transforms:
    email: # "md5"
  generatedFields:
    date:
      type: # "date"
      options:
        format: # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint: # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey:
  secret:
atom_feed:
  path: # blank (default) uses feed.xml
search: true #, false (default)
search_full_content: # true, false (default)
search_provider: # lunr (default), algolia, google
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false
google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true
# SEO Related
google_site_verification: FNK9kIcJfeWtRLkCANGljkyNuF_HuhxObiDLGGHeSpA
bing_site_verification: 2437E480C4CD67905F2F05B38D9D822B
yandex_site_verification: 8c56a149dae09e20
naver_site_verification:

# Social Sharing
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image: # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: Person
  name: # If the user or organization name differs from the site's name
  links:
  - "https://vk.com/dmmax_me"

# Analytics
analytics:
  provider: google #false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-134139084-2
    anonymize_ip: # true, false (default)


# Site Author
author:
  name: "Макс Димухаметов"
  avatar: "/assets/images/logo.png"
  bio: "Back-end разработчик Java/Kotlin"
  location: "Красноярск, Россия"
  email: "dmmax.me@gmail.com"
  links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/dmmax"
  - label: "VK"
    icon: "fab fa-fw fa-vk"
    url: "https://vk.com/dmmax_me"

# Site Footer
footer:
  links:
  - label: "Email"
    icon: "fab fa-fw fa-envelope-square"
    url: mailto:dmmax.me@gmail.com
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/dmmax"
  - label: "VK"
    icon: "fab fa-fw fa-vk"
    url: "https://vk.com/dmmax_me"

# Reading Files
include: ['_pages', '.htaccess']
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- .asset-cache
- .bundle
- .jekyll-assets-cache
- .sass-cache
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- /docs # ignore Minimal Mistakes /docs
- /test # ignore Minimal Mistakes /test
keep_files:
- .git
- .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Krasnoyarsk


# Plugins (previously gems:)
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
- jekyll-archives

# mimic GitHub Pages with --safe
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
# _posts
- scope:
    path: ""
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: # true
    share: true
    related: true
# _travel
- scope:
    path: ""
    type: travel
  values:
      layout: single
      author_profile: false
      share: true